\set ON_ERROR_STOP on

-- psql variables required by this script:
--   project_url: internal gateway URL, normally http://api-gw:8000
--   anon_key: legacy signed anon JWT generated by the self-hosted stack
--   ingestion_token: random token used only by scheduled ingestion

select vault.update_secret(
  id,
  :'project_url',
  'bolets_project_url',
  'Internal URL used by Bolets pg_cron jobs'
)
from vault.secrets
where name = 'bolets_project_url';

select vault.create_secret(
  :'project_url',
  'bolets_project_url',
  'Internal URL used by Bolets pg_cron jobs'
)
where not exists (
  select 1 from vault.secrets where name = 'bolets_project_url'
);

select vault.update_secret(
  id,
  :'anon_key',
  'bolets_legacy_anon_key',
  'Legacy anon JWT used by Bolets pg_cron jobs'
)
from vault.secrets
where name = 'bolets_legacy_anon_key';

select vault.create_secret(
  :'anon_key',
  'bolets_legacy_anon_key',
  'Legacy anon JWT used by Bolets pg_cron jobs'
)
where not exists (
  select 1 from vault.secrets where name = 'bolets_legacy_anon_key'
);

select vault.update_secret(
  id,
  :'ingestion_token',
  'bolets_ingestion_token',
  'Authorizes scheduled Bolets ingestion functions'
)
from vault.secrets
where name = 'bolets_ingestion_token';

select vault.create_secret(
  :'ingestion_token',
  'bolets_ingestion_token',
  'Authorizes scheduled Bolets ingestion functions'
)
where not exists (
  select 1 from vault.secrets where name = 'bolets_ingestion_token'
);

insert into public.pipeline_secrets (name, secret_hash)
values (
  'ingestion',
  encode(extensions.digest(:'ingestion_token', 'sha256'), 'hex')
)
on conflict (name) do update set
  secret_hash = excluded.secret_hash,
  rotated_at = pg_catalog.now();

do $$
begin
  if not exists (select 1 from vault.decrypted_secrets where name = 'bolets_project_url') then
    raise exception 'bolets_project_url was not configured';
  end if;
  if not exists (select 1 from vault.decrypted_secrets where name = 'bolets_legacy_anon_key') then
    raise exception 'bolets_legacy_anon_key was not configured';
  end if;
  if not exists (select 1 from vault.decrypted_secrets where name = 'bolets_ingestion_token') then
    raise exception 'bolets_ingestion_token was not configured';
  end if;
end
$$;
