/* External identifiers of the catalogue species: the Wikidata item and the
   GBIF backbone taxon key, resolved from the scientific name. Generated by
   scripts/build-species-identifiers.mts and reviewed by hand; an undefined
   field means the lookup found no exact species-rank match. These feed the
   Taxon sameAs links in the page JSON-LD. */

export interface SpeciesIdentifiers {
  /** Wikidata item id, e.g. "Q19740". */
  wikidata?: string;
  /** GBIF backbone taxon key, e.g. 2519407. */
  gbif?: number;
}

export const speciesIdentifiers: Record<string, SpeciesIdentifiers> = {
  "macrolepiota-procera": { wikidata: "Q243381", gbif: 8914748 }, // Macrolepiota procera
  "omphalotus-olearius": { wikidata: "Q1043730", gbif: 2538088 }, // Omphalotus olearius
  "gyromitra-esculenta": { wikidata: "Q900804", gbif: 5258510 }, // Gyromitra esculenta
  "coprinus-comatus": { wikidata: "Q275125", gbif: 7987658 }, // Coprinus comatus
  "chroogomphus-rutilus": { wikidata: "Q1491620", gbif: 2524996 }, // Chroogomphus rutilus
  "craterellus-lutescens": { wikidata: "Q1478429", gbif: 8871787 }, // Craterellus lutescens
  "marasmius-oreades": { wikidata: "Q752492", gbif: 2537250 }, // Marasmius oreades
  "agaricus-campestris": { wikidata: "Q234529", gbif: 5243458 }, // Agaricus campestris
  "clitocybe-rivulosa": { wikidata: "Q2720076", gbif: 2531052 }, // Collybia rivulosa — Collybia rivulosa (2023) is still filed as Clitocybe rivulosa
  "hygrophorus-russula": { wikidata: "Q2714680", gbif: 2538807 }, // Hygrophorus russula
  "entoloma-sinuatum": { wikidata: "Q1424216", gbif: 2539308 }, // Entoloma sinuatum
  "boletus-edulis": { wikidata: "Q19740", gbif: 5954958 }, // Boletus edulis
  "boletus-reticulatus": { wikidata: "Q26203726", gbif: 5954691 }, // Boletus reticulatus
  "boletus-aereus": { wikidata: "Q757127", gbif: 8733688 }, // Boletus aereus
  "boletus-pinophilus": { wikidata: "Q1415435", gbif: 5954949 }, // Boletus pinophilus
  "leccinellum-lepidum": { wikidata: "Q3829324", gbif: 11057661 }, // Leccinellum lepidum
  "amanita-verna": { wikidata: "Q571885", gbif: 5240320 }, // Amanita verna
  "cortinarius-orellanus": { wikidata: "Q1367003", gbif: 2528684 }, // Cortinarius orellanus
  "cortinarius-rubellus": { wikidata: "Q944328", gbif: 2528663 }, // Cortinarius rubellus — Wikidata labels the item with a common name; P225 is the binomial
  "craterellus-tubaeformis": { wikidata: "Q371126", gbif: 2554536 }, // Craterellus tubaeformis
  "hygrophoropsis-aurantiaca": { wikidata: "Q1265541", gbif: 2525710 }, // Hygrophoropsis aurantiaca
  "amanita-phalloides": { wikidata: "Q188643", gbif: 5240325 }, // Amanita phalloides
  "amanita-virosa": { wikidata: "Q472817", gbif: 5240323 }, // Amanita virosa
  "tricholoma-terreum": { wikidata: "Q27266", gbif: 5241808 }, // Tricholoma terreum
  "tricholoma-portentosum": { wikidata: "Q261047", gbif: 5241860 }, // Tricholoma portentosum
  "tricholoma-pardinum": { wikidata: "Q1928462", gbif: 7242174 }, // Tricholoma pardinum — Wikidata labels the item with a common name; P225 is the binomial
  "galerina-marginata": { wikidata: "Q248829", gbif: 8118872 }, // Galerina marginata
  "pleurotus-ostreatus": { wikidata: "Q186451", gbif: 2526530 }, // Pleurotus ostreatus
  "pleurotus-eryngii": { wikidata: "Q901105", gbif: 9075265 }, // Pleurotus eryngii
  "inocybe-erubescens": { wikidata: "Q107805287", gbif: 10776858 }, // Inosperma erubescens
  "hygrophorus-latitabundus": { wikidata: "Q1548745", gbif: 2538733 }, // Hygrophorus latitabundus
  "hygrophorus-eburneus": { wikidata: "Q1112614", gbif: 9053531 }, // Hygrophorus eburneus
  "hydnum-repandum": { wikidata: "Q13684", gbif: 2554716 }, // Hydnum repandum — Wikidata labels the item with a common name; P225 is the binomial
  "lactifluus-rugatus": { wikidata: "Q107882606", gbif: 7487285 }, // Lactifluus rugatus
  "russula-cyanoxantha": { wikidata: "Q246696", gbif: 2551542 }, // Russula cyanoxantha
  "russula-virescens": { wikidata: "Q677341", gbif: 2551423 }, // Russula virescens
  "hygrophorus-marzuolus": { wikidata: "Q727534", gbif: 7244099 }, // Hygrophorus marzuolus
  "rubroboletus-satanas": { wikidata: "Q26203731", gbif: 7722553 }, // Rubroboletus satanas
  "tylopilus-felleus": { wikidata: "Q633503", gbif: 2524910 }, // Tylopilus felleus
  "calocybe-gambosa": { wikidata: "Q731944", gbif: 8936224 }, // Calocybe gambosa
  "suillus-luteus": { wikidata: "Q816730", gbif: 7777157 }, // Suillus luteus
  "suillus-granulatus": { wikidata: "Q1142857", gbif: 8146046 }, // Suillus granulatus
  "morchella-esculenta": { wikidata: "Q1129282", gbif: 2594602 }, // Morchella esculenta
  "amanita-caesarea": { wikidata: "Q220662", gbif: 5240269 }, // Amanita caesarea
  "lepiota-brunneoincarnata": { wikidata: "Q2375450", gbif: 2535390 }, // Lepiota brunneoincarnata
  "paxillus-involutus": { wikidata: "Q518069", gbif: 5240002 }, // Paxillus involutus
  "calvatia-gigantea": { wikidata: "Q222449", gbif: 2536058 }, // Calvatia gigantea
  "lycoperdon-utriforme": { wikidata: "Q378497", gbif: 5243236 }, // Lycoperdon utriforme
  "lycoperdon-perlatum": { wikidata: "Q545130", gbif: 5243258 }, // Lycoperdon perlatum
  "ramaria-formosa": { wikidata: "Q1257786", gbif: 5238663 }, // Ramaria formosa
  "ramaria-aurea": { wikidata: "Q1479710", gbif: 5238642 }, // Ramaria aurea
  "lepista-nuda": { wikidata: "Q29362", gbif: 5242048 }, // Lepista nuda
  "lactarius-deliciosus": { wikidata: "Q62138", gbif: 5248629 }, // Lactarius deliciosus
  "lactarius-chrysorrheus": { wikidata: "Q1530713", gbif: 5248610 }, // Lactarius chrysorrheus
  "amanita-pantherina": { wikidata: "Q45547", gbif: 8961574 }, // Amanita pantherina
  "cyclocybe-cylindracea": { wikidata: "Q97665399", gbif: 8138987 }, // Cyclocybe cylindracea
  "amanita-muscaria": { wikidata: "Q131227", gbif: 8168319 }, // Amanita muscaria
  "cantharellus-cibarius": { wikidata: "Q188749", gbif: 5249504 }, // Cantharellus cibarius
  "lactarius-sanguifluus": { wikidata: "Q961386", gbif: 5248648 }, // Lactarius sanguifluus
  "lactarius-torminosus": { wikidata: "Q865540", gbif: 8122710 }, // Lactarius torminosus
  "tuber-melanosporum": { wikidata: "Q1093314", gbif: 5258468 }, // Tuber melanosporum
  "craterellus-cornucopioides": { wikidata: "Q857903", gbif: 2554662 }, // Craterellus cornucopioides — Wikidata labels the item with a common name; P225 is the binomial
};

/** The `sameAs` URLs of a species' Taxon markup, empty when nothing is known. */
export function speciesSameAs(speciesId: string): string[] {
  const ids = speciesIdentifiers[speciesId];
  if (!ids) return [];
  return [
    ...(ids.wikidata ? [`https://www.wikidata.org/wiki/${ids.wikidata}`] : []),
    ...(ids.gbif ? [`https://www.gbif.org/species/${ids.gbif}`] : []),
  ];
}
