/* Looks up the Wikidata item and the GBIF backbone key of every catalogue
   species by scientific name and writes data/species-identifiers.ts. Review
   the diff by hand: the script keeps a match only when the label returned
   equals the scientific name, and lists the rest for manual resolution.

   Run: npm run species:identifiers */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { catalogueSpecies } from "@/data/catalogue";

interface Match { speciesId: string; scientificName: string; wikidata?: string; gbif?: number; note?: string }

/* Matches resolved by hand where the automatic lookup fails: the record's
   name is a recent recombination the databases have not adopted, or the
   Wikidata English label is a common name rather than the binomial. */
const MANUAL: Record<string, { wikidata?: string; gbif?: number; note: string }> = {
  "clitocybe-rivulosa": { wikidata: "Q2720076", gbif: 2531052, note: "Collybia rivulosa (2023) is still filed as Clitocybe rivulosa" },
  "craterellus-cornucopioides": { wikidata: "Q857903", note: "Wikidata labels the item with a common name; P225 is the binomial" },
  "cortinarius-rubellus": { wikidata: "Q944328", note: "Wikidata labels the item with a common name; P225 is the binomial" },
  "tricholoma-pardinum": { wikidata: "Q1928462", note: "Wikidata labels the item with a common name; P225 is the binomial" },
  "hydnum-repandum": { wikidata: "Q13684", note: "Wikidata labels the item with a common name; P225 is the binomial" },
};

async function wikidataItem(name: string) {
  const url = `https://www.wikidata.org/w/api.php?action=wbsearchentities&search=${encodeURIComponent(name)}&language=en&format=json&limit=5`;
  const data = await (await fetch(url, { headers: { "user-agent": "bolets.app species identifiers (aleix@ventayol.cat)" } })).json() as { search: Array<{ id: string; label: string; description?: string }> };
  return data.search.find((hit) => hit.label.toLowerCase() === name.toLowerCase() && !/variety|subspecies|form of/i.test(hit.description ?? ""))?.id;
}

async function gbifKey(name: string) {
  const url = `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}&kingdom=Fungi&strict=true`;
  const data = await (await fetch(url)).json() as { usageKey?: number; matchType?: string; rank?: string; canonicalName?: string };
  return data.matchType === "EXACT" && data.rank === "SPECIES" && data.canonicalName?.toLowerCase() === name.toLowerCase() ? data.usageKey : undefined;
}

const matches: Match[] = [];
for (const species of catalogueSpecies) {
  const name = species.identity.scientificName;
  const [found, gbifFound] = await Promise.all([wikidataItem(name), gbifKey(name)]);
  const manual = MANUAL[species.speciesId];
  const wikidata = manual?.wikidata ?? found;
  const gbif = manual?.gbif ?? gbifFound;
  matches.push({ speciesId: species.speciesId, scientificName: name, wikidata, gbif, note: manual?.note });
  console.log(`${species.speciesId.padEnd(34)} ${name.padEnd(32)} ${wikidata ?? "—"}\t${gbif ?? "—"}`);
}

const lines = matches.map((match) => {
  const fields = [`wikidata: ${match.wikidata ? `"${match.wikidata}"` : "undefined"}`, `gbif: ${match.gbif ?? "undefined"}`];
  return `  "${match.speciesId}": { ${fields.join(", ")} }, // ${match.scientificName}${match.note ? ` — ${match.note}` : ""}`;
});
const source = `/* External identifiers of the catalogue species: the Wikidata item and the
   GBIF backbone taxon key, resolved from the scientific name. Generated by
   scripts/build-species-identifiers.mts and reviewed by hand; an undefined
   field means the lookup found no exact species-rank match. These feed the
   Taxon sameAs links in the page JSON-LD. */

export interface SpeciesIdentifiers {
  /** Wikidata item id, e.g. "Q19740". */
  wikidata?: string;
  /** GBIF backbone taxon key, e.g. 2519407. */
  gbif?: number;
}

export const speciesIdentifiers: Record<string, SpeciesIdentifiers> = {
${lines.join("\n")}
};

/** The \`sameAs\` URLs of a species' Taxon markup, empty when nothing is known. */
export function speciesSameAs(speciesId: string): string[] {
  const ids = speciesIdentifiers[speciesId];
  if (!ids) return [];
  return [
    ...(ids.wikidata ? [\`https://www.wikidata.org/wiki/\${ids.wikidata}\`] : []),
    ...(ids.gbif ? [\`https://www.gbif.org/species/\${ids.gbif}\`] : []),
  ];
}
`;
await writeFile(join(import.meta.dirname, "..", "data", "species-identifiers.ts"), source);
const missing = matches.filter((match) => !match.wikidata || !match.gbif);
console.log(`\n${matches.length} species, ${missing.length} with a missing id${missing.length ? ": " + missing.map((m) => m.scientificName).join(", ") : ""}`);
